Workshop
corndel-swe/topsify-annaarnold96 pull request #3
Opened 2024-10-07 14:57 UTC by annaarnold96

Did terribly. Had a bit of a breakdown ngl. Couldn't figure out how to turn the list into objects that I could actually use.

2024-10-07 15:03 UTC, pablobgldo commented on cli/pom.xml
> +        <groupId>com.fasterxml.jackson.core</groupId>
Nice use of dependencies

2024-10-07 15:06 UTC, pablobgldo commented on cli/src/main/java/org/example/Main.java
> +    public class User {
Maybe you could try create the User class in another file (User.java) and add getters to access them from Main.java?

2024-10-07 15:06 UTC, pablobgldo commented on cli/src/main/java/org/example/Main.java
> +        Path filePath = Paths.get("reports", "users.json");
Iconic way of defining both paths of interest - will be replicating this in my project later!

2024-10-07 15:08 UTC, pablobgldo commented on cli/src/main/java/org/example/Main.java
> +        Files.write(newFilePath,test);
I assume it's not finished but you could try write a list of 'SQL Insert statement' strings into the newFilePath and do some logic before to create each string?

2024-10-07 15:09 UTC, pablobgldo requested changes
Keep up the good work!! You are so close!

2024-10-08 09:33 UTC, Charlie-robin approved these changes
Good to merge :)

2024-10-08 12:47 UTC, closed without merging